---
title: "Example_report_rmarkdown"
author: "Adeshina Odugbemi"
output: github_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## This document

The aim of this document is to analyze inflammation data from the r-novice-inflammation dataset.

You can find the original data here: <http://swcarpentry.github.io/r-novice-inflammation/setup.html>

### Method

A function to create plots for individual files was created:

```{r}

analyze <- function(filename) {
  
  # takes a filename with relative path
  # reads the csv
  # calculates avg, max, min
  # creates panel of 3 plots
  
  dat <- read.csv(file = filename, header = FALSE)
  
  
  # calculate avg, max, min by column (per day)
  
  avg_day_inflammation <- apply(dat, 2, mean)
  
  max_day_inflammation <- apply(dat, 2, max)
  
  min_day_inflammation <- apply(dat, 2, min)
  
  
  # plot avg, max, min daily inflammation
  
  par(mfrow = c(1, 3)) # set up 1x3 plot panel
  
  plot(avg_day_inflammation, main = filename)
  
  plot(max_day_inflammation, main = filename)
  
  plot(min_day_inflammation, main = filename)
  
  par(mfrow = c(1, 1)) # return plot setting to 1x1
  
}

```
